aludeveloper/alx-angular-surveys

src/viewer/templates/material/mw-form-question.html
- added 3 empty row to textarea.
=> textarea update

src/viewer/templates/material/mw-form-question.html
=> added md-datepicker

src/builder/form-builder-options.service.js, src/builder/form-page-builder.directive.js, src/builder/form-page-element-builder.directive.js, src/builder/form-videolink-builder.directive.js, src/builder/templates/material/mw-form-page-builder.html, src/builder/templates/material/mw-form-page-element-builder.html, src/builder/templates/material/mw-form-videolink-builder.html, src/viewer/form-viewer.directive.js, src/viewer/templates/material/mw-form-viewer-content.html
- added video link component which takes embedded youtube code as input
- trello - https://trello.com/c/f5bpuOHp
- screenshots
=> added videolink component

src/builder/question-offered-answer-list-builder.directive.js, src/builder/templates/bootstrap/mw-question-offered-answer-list-builder.html, src/builder/templates/material/mw-question-offered-answer-list-builder.html
- flat csv file import for select question type.
- merged code from alu survey
=> Feature csv select

bower.json, demo-material/demo.html, src/viewer/form-question.directive.js, src/viewer/templates/material/mw-form-question.html
- date format for md-datepicker changed to dd-mm-yyyy
- dependency - moment.js
=> date format changed to dd-mm-yyyy

styles/form-viewer-material.scss
- increased top padding for all questions
=> increased top padding for questions

src/viewer/templates/material/mw-form-question.html, styles/form-viewer-material.scss
- replaced character count down with word count down for textarea question
=> word count for textarea

src/viewer/templates/material/mw-form-viewer-content.html
- fail state for conditional paragraph
-
=> fail text for conditional para

dist/form-viewer.js, src/viewer/form-viewer.directive.js, src/viewer/templates/material/mw-form-viewer-content.html
what does this PR do?
- It changes button text I understand at second last page of stage 1
Screenshots -
=> button text changed

src/viewer/templates/material/mw-form-question.html, styles/form-viewer-material.scss
- changes on default active color of dropdown
- radio layout in column
- remove button shadow
- 
screen shot
-
=> style changes

src/viewer/form-viewer.directive.js
=> added stage data for sf

bower.json, demo-material/demo.html, i18n/en/angular-surveys.json, src/builder/form-builder-options.service.js, src/builder/templates/material/mw-form-question-builder.html, src/utils/form-response-utils.service.js, src/viewer/form-question.directive.js, src/viewer/form-viewer.directive.js, src/viewer/templates/material/mw-form-question.html, src/viewer/templates/material/mw-form-viewer-content.html, styles/form-viewer-material.scss
- added telephone question type which validates phone number by country
=> telephone with country code

src/utils/form-response-utils.service.js
- sending concatenated (country code + number) payload for phone number.
=> phone payload fixed

dist/form-utils.js, src/utils/form-response-utils.service.js, src/viewer/form-question.directive.js
- if checks for linked question response
- merging linked question with response
=> linked question response

src/utils/form-response-utils.service.js
- fixed issue with repopulating phone field
=> phone repopulate fix

src/builder/templates/material/mw-question-offered-answer-list-builder.html, src/utils/form-response-utils.service.js, src/viewer/form-question.directive.js, src/viewer/templates/material/mw-form-question.html
- made select linked question
- multiple questions will be linked to input type select
=> feature- select-linked-question

src/viewer/form-question.directive.js, src/viewer/templates/material/mw-form-question.html
=> checkbox issue fixed

src/builder/templates/material/mw-form-question-builder.html
- changed salesforce select menu to material design
- sfkey is now sent as string instead of object
=> material salesforce select menu

src/viewer/form-question.directive.js
- country code is auto selected for telephone question
=> telephone auto select country

src/builder/question-offered-answer-list-builder.directive.js
=> question radio files undefined checks

src/builder/templates/material/mw-form-page-builder.html, src/builder/templates/material/mw-form-question-builder.html, src/viewer/form-question.directive.js, src/viewer/templates/material/mw-form-question.html
- upload file size limit increased to 5mb
- trello card - https://trello.com/c/0qQBJIPO
=> upload file size limit increased to 5mb

src/viewer/form-viewer.directive.js, src/viewer/templates/material/mw-form-viewer-content.html
- It adds value of SFkey and display.
- src/viewer/form-viewer.directive.js
- src/viewer/templates/material/mw-form-viewer-content.html
- No
- 
- No
- Are there changes to database structures? 
- No
- Are there dependencies to be added? 
- No
=> survey side paragraph sfkey

src/viewer/form-viewer.directive.js, src/viewer/templates/material/mw-form-viewer-content.html, styles/form-viewer-material.scss
- multi column responsive fixes
- paragraph fixed
=> Feature multicolumn styling

i18n/en/angular-surveys.json
it replaces text "I Understand" with "Save & Proceed"
=> i understand button text replaced by save and proceed

src/builder/form-builder.directive.js, src/builder/form-page-builder.directive.js, src/builder/form-page-element-builder.directive.js, src/builder/form-question-builder.directive.js, src/builder/question-offered-answer-list-builder.directive.js, src/builder/templates/material/mw-form-page-builder.html, src/builder/templates/material/mw-form-page-element-builder.html, src/builder/templates/material/mw-form-question-builder.html, src/builder/templates/material/mw-question-offered-answer-list-builder.html, src/utils/form-response-utils.service.js, src/viewer/form-question.directive.js, src/viewer/form-viewer.directive.js, src/viewer/templates/material/mw-form-question.html
- fixed radio button default select issue.
- linked question drop down shows current page elements.
=> Feature current with linked ques

src/builder/templates/material/mw-form-question-builder.html
- It changes required condition for char limit.
- src/builder/templates/material/mw-form-question-builder.html
- Check it on page
- No
- 
- No
- Are there changes to database structures? 
- No
- Are there dependencies to be added? 
- No
=> required condition for char limit changed

src/builder/templates/material/mw-form-videolink-builder.html
- fixed videolink preview in builder
=> videolink builder preview fixed

src/viewer/form-viewer.directive.js
- bug missing a slash paragraph api endpoint
=> slash missing in paragraph api end point
